### ISSUE TITLE
Fluency builder not supported

### ISSUE THREAD

**Issue by Cougar16** [m1dugh/RosettaStonks#19]
Time is not being added when we add a time value there in fluency builder !
Please fix it ! I already commented about that in the last issue !

**Comment by m1dugh** [comment]
What didn't you get in my last answer ?
If you can't use the provided bug template and precisely describe what your bug is, I won't even try to help you.
As I said, it works on my machine, so if it doesn't work on yours, I'm not gonna fix something if I don't know what it is.

I will keep closing your issue till you precisely and respectfully describe what your problem is using the provided template.

*Remember that I am not the one affected by the issue, therefore, I don't really care whether you validate your due time or not.*

**Comment by BXRl** [comment]
yep you cant add time to fluency blender i tried with multiple accounts and with 2 devices and the problem is the same from a1 . a2 time getting added b1 b2 c1 c2 nope no time getting added

**Comment by Cougar16** [comment]
The developer fixed it ! Try again ! Maybe you didn't load the extension correctly.

**Comment by Cougar16** [comment]
> yep you cant add time to fluency blender i tried with multiple accounts and with 2 devices and the problem is the same from a1 . a2 time getting added b1 b2 c1 c2 nope no time getting added

The developer fixed it ! Try again ! Maybe you didn't load the extension correctly.

**Comment by BXRl** [comment]
it was working perfectly but i dont think it work anymore for more than b1
